const planetsData = [
  {
    className: "planet1",
    rotationSpeed: 60,
    scrollSpeed: "-70%",
    speedX: 0.01,
    speedY: 0.002,
    speedZ: 0.002,
    rotation: 10,
  },
  {
    className: "planet2",
    rotationSpeed: 70,
    scrollSpeed: "-80%",
    speedX: 0.1,
    speedY: 0.02,
    speedZ: 0.2,
    rotation: 10,
  },
  {
    className: "planet3",
    rotationSpeed: 50,
    scrollSpeed: "-120%",
    speedX: 0.1,
    speedY: 0.02,
    speedZ: 0.2,
    rotation: 10,
  },
  {
    className: "planet4",
    rotationSpeed: 50,
    scrollSpeed: "-100%",
    speedX: 0.1,
    speedY: 0.02,
    speedZ: 0.2,
    rotation: 10,
  },
  {
    className: "planet5",
    rotationSpeed: 50,
    scrollSpeed: "-200%",
    speedX: 0.1,
    speedY: 0.02,
    speedZ: 0.2,
    rotation: 10,
  },
  {
    className: "planet6",
    rotationSpeed: 50,
    scrollSpeed: "-300%",
    speedX: 0.1,
    speedY: 0.02,
    speedZ: 0.2,
    rotation: 10,
  },
  {
    className: "planet7",
    rotationSpeed: 50,
    scrollSpeed: "-20%",
    speedX: 0.1,
    speedY: 0.02,
    speedZ: 0.2,
    rotation: 10,
  },
  {
    className: "planet8",
    rotationSpeed: 50,
    scrollSpeed: "-80%",
    speedX: 0.1,
    speedY: 0.02,
    speedZ: 0.2,
    rotation: 10,
  },
  {
    className: "planet9",
    rotationSpeed: 50,
    scrollSpeed: "-70%",
    speedX: 0.1,
    speedY: 0.02,
    speedZ: 0.2,
    rotation: 10,
  },
  {
    className: "planet10",
    rotationSpeed: 50,
    scrollSpeed: "-90%",
    speedX: 0.1,
    speedY: 0.02,
    speedZ: 0.2,
    rotation: 10,
  },
  {
    className: "planet11",
    rotationSpeed: 50,
    scrollSpeed: "-50%",
    speedX: 0.1,
    speedY: 0.02,
    speedZ: 0.2,
    rotation: 10,
  },
  {
    className: "bigPlanet",
    rotationSpeed: 50,
    scrollSpeed: "-70%",
    speedX: 0.1,
    speedY: 0.02,
    speedZ: 0.2,
    rotation: 10,
  },
];

export default planetsData;
